#!/bin/sh
# source common files and do basic checkings

. /usr/share/ds-matricula-plugin/matricula-common-scripts/ausias-user-manager-common

ldap2xml() {
	SED_RULE="/^$/d;/^dn:/s%^.*$%\n<alumno%;"

	ATTRIB_LIST="uid uidNumber employeeNumber sambaSID gidNumber sambaPrimaryGroupSID gecos"
	for f in $ATTRIB_LIST ; do
		case "$f" in
			uid)
				F="login"
				;;
			gecos) 
        	                F="nombre_comp"
                	        ;;

			*)
				F="$f"
				;;
		esac
		SED_RULE="${SED_RULE}/^$f:/{s%^$f: % $F=\"%;s%\$%\"%};"

	done

	SED_RULE="${SED_RULE}/^[[:blank:]]*login=/{p;s%login%DNI_NORM%;s%=\".\(.*$\)%=\"\U\1%;/=\".[A-Z]/s%=\"\(.\)\(.\)%=\"\2\1%}"
	ALU_GID="$(getent group ALUMNOS  |cut -f 3 -d :)"
	# get ldif
	#TMP_FILE="$(tempfile)"
	ldapsearch -LLL -x -b "dc=centro,dc=com" -D "$masterDN" -w "$masterPw" "(&(objectClass=posixAccount)(gidnumber=$ALU_GID))" $ATTRIB_LIST | sed -e "$SED_RULE" |sed '1d;/^$/s%^%/>%;$a/>'
}
 

# more checks
[ "$1" = "-y" ] || user_confirmation "This script deletes from ldap server all users tagged as 'deleted' ('borrado = 1') in mySQL itaca.alumnos table"

#Paso 2 
# extraer en una tabla a los alumnos existentes en el LDAP (login con formato a[[:digit:]]+).Tabla ldap_tmp
# buscar por login todos los alumnos de la tabla ldap_tmp que no existan en la tabla de alumnos
# añadirlos y marcarlos como manuales (alumnos.manual="1")
# el campo DNI_NORM se construye a partir del campo login de la tabla ldap

TMP_XML="$(tempfile)"
ldap2xml > $TMP_XML
mysql --local-infile=1 -N -B -e "use itaca; truncate table ldap_temp; load xml local infile '$TMP_XML' into table ldap_temp character set utf8 rows identified by '<alumno>';"

# update DNI for legacy alXXXXX accounts
mysql -N -B -e "use itaca; delete from ldap_temp where login='alumno'; update ldap_temp, alumnos set ldap_temp.DNI_NORM=alumnos.DNI_NORM where ldap_temp.login like 'al%' and ldap_temp.login=alumnos.login"

# insert manual users 
mysql -N -B -e "use itaca; INSERT INTO alumnos (nombre, DNI_NORM, manual) select nombre_comp as nombre,DNI_NORM, '1' as manual from ldap_temp where DNI_NORM not in (select DNI_NORM from alumnos);"


#Paso 3
# en la tabla alumnos, poner el campo borrado="1" a todos los alumnos que tengan los campos:
# borrado="0" && manual="0" && DNI_NORM no existe en dniok ("table 14", alumnos matriculados en el curso actual)
# update alumnos set borrado="1" where borrado="0" and manual=”0” and dni_norm not in (select dniok from `TABLE 14`)

mysql -N -B -e "use itaca; update alumnos set borrado='1' where borrado='0' and manual='0' and DNI_NORM not in (select dniok from itaca_temp);"


#Paso 4
# copiar el balance desde la tabla papercut.tbl_account.balance al campo balance de los alumnos con borrado="1"
#update alumnos, papercut.tbl_account set alumnos.balance=papercut.tbl_account.balance 
#where login=papercut.tbl_account.account_name and alumnos.borrado="1"

mysql -N -B -e "use itaca; update alumnos, papercut.tbl_account set alumnos.balance=papercut.tbl_account.balance where login=papercut.tbl_account.account_name and alumnos.borrado='1';"

#Paso 5 
# eliminar a todos los alumnos con el campo alumnos.borrado="1" en el LDAP y modificar el campo borrado="2"
# TODO: borrar la foto del servidor!!
TMP_FILE="$(tempfile)"
mysql -N -B -e "use itaca; select login from alumnos where borrado='1';" > "$TMP_FILE"

[ -s "$TMP_FILE" ] || die "Error generating file from mysql"

cat "$TMP_FILE" |while read l; do
	echo "Deleting user: $l"
	smbldap-userdel $l || true
done
# falta poner la fecha de borrado !!!!!!
mysql -N -B -e "use itaca; update alumnos set borrado='2', fecha_borrado=NOW() where borrado='1';"

rm -f "$TMP_FILE"
exit 0

