#!/bin/bash

. /usr/share/ds-matricula-plugin/matricula-common-scripts/ausias-user-manager-common

die() {
	echo "$1" >&2
	exit 1
}

IMAGE_DIR="/srv/carnets/alumnos"
NOIMAGE="NOBODY.jpg"

#convertir a uppercase

# thanks to http://unix.stackexchange.com/questions/84229/change-filename-from-lowercase-to-uppercase-recursively
( cd $IMAGE_DIR; rename 's/^([^.]*)\.(.*)$/\U$1\L.$2/' *; )

chmod 664 $IMAGE_DIR/*
chown datastore:datastore $IMAGE_DIR/*

#  Listar alumnos no borrados y buscar foto

mysql -N -B -e "use itaca; select DNI_NORM from alumnos where borrado='0' and foto != concat(DNI_NORM,'.jpg');" |while read dni; do
	IMAGE_FILE="${dni}.jpg"
	if [ ! -e "$IMAGE_DIR/$IMAGE_FILE" ]; then
		IMAGE_FILE="$NOIMAGE"
	fi
	mysql -N -B -e "use itaca; update alumnos set foto = '$IMAGE_FILE' where DNI_NORM = '$dni';"
done

# imagenes huerfanas

TMP_FILE="$(tempfile)"
TMP_FILE2="$(tempfile)"

#mysql -N -B -e "use itaca; select DNI_NORM from alumnos where borrado='0' ;" > $TMP_FILE
mysql -N -B -e "use itaca; select DNI_NORM from alumnos ;" > $TMP_FILE

ls -1 $IMAGE_DIR/*.jpg 2>/dev/null | while read F; do
	f="$(basename "$F" ".jpg")"
	if ! grep -Fxq "$f" $TMP_FILE ; then
		echo "$f" >> $TMP_FILE2
	fi
done

cat $TMP_FILE2

# import to mysql ...
IMPORT_SQL="use itaca; delete from fotos_huerfanas; load data local infile '$TMP_FILE2' into table fotos_huerfanas;"
mysql --local-infile=1 -N -B -e "$IMPORT_SQL"
rm -f $TMP_FILE $TMP_FILE2


exit 0
