#!/bin/sh


echo "WARNING!!!: This script deletes from ldap server all users tagged as 'deleted' ('borrado = 1') in mySQL itaca.alumnos table"
echo "¿Do you want to proceed? (Write 'YES' in uppercase to continue)"
read a
[ "$a" = "YES" ] || die "Aborted due to user input"

# source common files and do basic checkings

. /usr/share/ds-matricula-plugin/matricula-common-scripts/ausias-user-manager-common

# common funcs
usage(){
	die "$0 <CSV_FILE>"
}


# more checks

[ "$1" ] || usage
CSV_FILE="$1"
[ -r "$CSV_FILE" ] || die "Error reading $CSV_FILE"

#Paso 1
#convertir el csv de itaca (alumnos matriculados en el curso actual) a una tabla en mysql (ahora "table 14"). Import desde mysql

TMP_XML="$(tempfile)"
./csv2ldap "$CSV_FILE" "$TMP_XML"

#Paso 2 
# extraer en una tabla a los alumnos existentes en el LDAP (login con formato a[[:digit:]]+).Tabla ldap_tmp
# buscar por login todos los alumnos de la tabla ldap_tmp que no existan en la tabla de alumnos
# añadirlos y marcarlos como manuales (alumnos.manual="1")
# el campo DNI_NORM se construye a partir del campo login de la tabla ldap 

#Paso 3
# en la tabla alumnos, poner el campo borrado="1" a todos los alumnos que tengan los campos:
# borrado="0" && manual="0" && DNI_NORM no existe en dniok ("table 14", alumnos matriculados en el curso actual)
# update alumnos set borrado="1" where borrado="0" and manual=”0” and dni_norm not in (select dniok from `TABLE 14`)

#Paso 4
# copiar el balance desde la tabla papercut.tbl_account.balance al campo balance de los alumnos con borrado="1"
#update alumnos, papercut.tbl_account set alumnos.balance=papercut.tbl_account.balance 
#where login=papercut.tbl_account.account_name and alumnos.borrado="1"

#Paso 5 
# eliminar a todos los alumnos con el campo alumnos.borrado="1" en el LDAP y modificar el campo borrado="2"
TMP_FILE="$(tempfile)"
echo "Enter mySQL root password:"
mysql -u root -p -N -B -e "use itaca; select login from alumnos where borrado='1';" > "$TMP_FILE"

[ -s "$TMP_FILE" ] || die "Error generating file from mysql"

cat "$TMP_FILE" |while read l; do
	echo "Deleting user: $l"
	smbldap-userdel $l || true
done

echo "Enter mySQL root password:"
mysql -u root -p -N -B -e "use itaca; update alumnos set borrado='2' where borrado='1';"

rm -f "$TMP_FILE"

