#!/bin/sh
die() {
	echo "$1" >&2
	exit 1
}

usage(){
	die "Usage: $0 <LOGIN>"
}

strip_dni(){
        # remove letters and select the last 8 chars
        echo "$1" |sed "s%[a-zA-Z]%%g;s%^.*\(.\{8\}\)$%\1%"
}


get_from_db(){
	DB_FIELD="$1"
	mysql -N -B -e "use itaca; select $DB_FIELD from alumnos where login='$login'"
}

# main
# ----
[ $(id -u) -eq 0 ] || die "You must be root to run this script"

# check configuration files
for f in /etc/smbldap-tools/smbldap_bind.conf  /etc/smbldap-tools/smbldap.conf; do
	[ -r "$f" ] || die "Missing configuration file $f"
	. $f
done
[ -r /root/.my.cnf ] || die "Missing mysql configurarion in /root/.my.cnf"
export HOME=/root

# test data
login="$1"
[ "$login" ] || usage
getent passwd "$login" >/dev/null || die "Alumno $login not exists in LDAP"

INIT_PASS="$(get_from_db "NIA")"
[ "$INIT_PASS" ] || INIT_PASS="$login"

echo "${INIT_PASS}\n${INIT_PASS}" |smbldap-passwd "$login" || die "Error setting password"
echo "Password set to '$INIT_PASS'"

exit 0

